index:
  index_id: 'fitbir_data_dictionary'
  summary: "FITBIR Data Dictionary Embeddings:"
  filepath_input: 'C:/Users/Kevin/Desktop/Coding/BRICS/brics-crossmap/brics_crossmap/data_dictionary/storage/test/test.csv'
  filepath_update: 'C:/Users/Kevin/Desktop/Coding/BRICS/brics-crossmap/brics_crossmap/data_dictionary/storage/test/update-upsert_test.csv'
  storage_path_root: 'C:/Users/Kevin/Desktop/Coding/BRICS/brics-crossmap/brics_crossmap/data_dictionary/storage/test/'
  storage_paths_indices:
  collections:
    embed:
      id_column: 'variable name'
      columns: &columns
        - 'title'
        - 'definition'
      model_name: 'pritamdeka/PubMedBERT-mnli-snli-scinli-scitail-mednli-stsb'
      model_version:
      model_kwargs:
        batch_size: 500
        device: 'cpu'
        normalize_embeddings: True
    names: *columns
    max_batch_size: 500
    distance_metric: {"hnsw:space": "cosine"}
    metadata_columns:
      - 'variable name'
      - 'title'
      - 'element type'
      - 'definition'
      - 'short description'
      - 'datatype'
      - 'input restriction'
      - 'minimum value'
      - 'maximum value'
      - 'data element concept identifiers'
      - 'data element concept names'
      - 'permissible values'
      - 'permissible value descriptions'
      - 'permissible value concept identifiers'
      - 'permissible value concept names'
      - 'unit of measure'
      - 'preferred question text'
      - 'creation date'
      - 'last change date'
